# Generated by Django 5.1.3 on 2025-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarforms', '0002_alter_solardatas_options_solardatas_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solardatas',
            name='preferred_contact_date',
        ),
        migrations.AddField(
            model_name='solardatas',
            name='preferred_contact_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่สะดวกให้ติดต่อ'),
        ),
    ]
