# Generated by Django 5.1.3 on 2025-01-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarforms', '0003_remove_solardatas_preferred_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solardatas',
            name='preferred_contact_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ช่วงเวลาที่สะดวกในการติดตั้ง'),
        ),
        migrations.AlterField(
            model_name='solardatas',
            name='preferred_survey_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สะดวกในการสำรวจหน้างาน'),
        ),
    ]
